language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - 7.0

os:
 - linux
 - osx

env:
  global:
    - MOODLE_BRANCH=MOODLE_31_STABLE
    - IGNORE_PATHS=library/OAuth

  matrix:
    - DB=pgsql
    - DB=mysqli

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat